#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankrekening
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Bankrekening")]
	public partial class BankrekeningDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTypen(Typen instance);
    partial void UpdateTypen(Typen instance);
    partial void DeleteTypen(Typen instance);
    partial void InsertKlanten(Klanten instance);
    partial void UpdateKlanten(Klanten instance);
    partial void DeleteKlanten(Klanten instance);
    partial void InsertRekeningen(Rekeningen instance);
    partial void UpdateRekeningen(Rekeningen instance);
    partial void DeleteRekeningen(Rekeningen instance);
    #endregion
		
		public BankrekeningDataContext() : 
				base(global::Bankrekening.Properties.Settings.Default.BankrekeningConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BankrekeningDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BankrekeningDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BankrekeningDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BankrekeningDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Typen> Typens
		{
			get
			{
				return this.GetTable<Typen>();
			}
		}
		
		public System.Data.Linq.Table<Klanten> Klantens
		{
			get
			{
				return this.GetTable<Klanten>();
			}
		}
		
		public System.Data.Linq.Table<Rekeningen> Rekeningens
		{
			get
			{
				return this.GetTable<Rekeningen>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Typen")]
	public partial class Typen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Naam;
		
		private double _Rente;
		
		private double _MaxOpname;
		
		private System.Nullable<bool> _Boete;
		
		private EntitySet<Rekeningen> _Rekeningens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNaamChanging(string value);
    partial void OnNaamChanged();
    partial void OnRenteChanging(double value);
    partial void OnRenteChanged();
    partial void OnMaxOpnameChanging(double value);
    partial void OnMaxOpnameChanged();
    partial void OnBoeteChanging(System.Nullable<bool> value);
    partial void OnBoeteChanged();
    #endregion
		
		public Typen()
		{
			this._Rekeningens = new EntitySet<Rekeningen>(new Action<Rekeningen>(this.attach_Rekeningens), new Action<Rekeningen>(this.detach_Rekeningens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naam", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Naam
		{
			get
			{
				return this._Naam;
			}
			set
			{
				if ((this._Naam != value))
				{
					this.OnNaamChanging(value);
					this.SendPropertyChanging();
					this._Naam = value;
					this.SendPropertyChanged("Naam");
					this.OnNaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rente", DbType="Float NOT NULL")]
		public double Rente
		{
			get
			{
				return this._Rente;
			}
			set
			{
				if ((this._Rente != value))
				{
					this.OnRenteChanging(value);
					this.SendPropertyChanging();
					this._Rente = value;
					this.SendPropertyChanged("Rente");
					this.OnRenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxOpname", DbType="Float NOT NULL")]
		public double MaxOpname
		{
			get
			{
				return this._MaxOpname;
			}
			set
			{
				if ((this._MaxOpname != value))
				{
					this.OnMaxOpnameChanging(value);
					this.SendPropertyChanging();
					this._MaxOpname = value;
					this.SendPropertyChanged("MaxOpname");
					this.OnMaxOpnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Boete", DbType="Bit")]
		public System.Nullable<bool> Boete
		{
			get
			{
				return this._Boete;
			}
			set
			{
				if ((this._Boete != value))
				{
					this.OnBoeteChanging(value);
					this.SendPropertyChanging();
					this._Boete = value;
					this.SendPropertyChanged("Boete");
					this.OnBoeteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Typen_Rekeningen", Storage="_Rekeningens", ThisKey="Naam", OtherKey="Type")]
		public EntitySet<Rekeningen> Rekeningens
		{
			get
			{
				return this._Rekeningens;
			}
			set
			{
				this._Rekeningens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rekeningens(Rekeningen entity)
		{
			this.SendPropertyChanging();
			entity.Typen = this;
		}
		
		private void detach_Rekeningens(Rekeningen entity)
		{
			this.SendPropertyChanging();
			entity.Typen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klanten")]
	public partial class Klanten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BSN;
		
		private string _Voorletters;
		
		private string _Voornaam;
		
		private string _Achternaam;
		
		private string _Adres;
		
		private string _Postcode;
		
		private string _Woonplaats;
		
		private string _Telefoonnummer;
		
		private string _Email;
		
		private EntitySet<Rekeningen> _Rekeningens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBSNChanging(string value);
    partial void OnBSNChanged();
    partial void OnVoorlettersChanging(string value);
    partial void OnVoorlettersChanged();
    partial void OnVoornaamChanging(string value);
    partial void OnVoornaamChanged();
    partial void OnAchternaamChanging(string value);
    partial void OnAchternaamChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    partial void OnWoonplaatsChanging(string value);
    partial void OnWoonplaatsChanged();
    partial void OnTelefoonnummerChanging(string value);
    partial void OnTelefoonnummerChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Klanten()
		{
			this._Rekeningens = new EntitySet<Rekeningen>(new Action<Rekeningen>(this.attach_Rekeningens), new Action<Rekeningen>(this.detach_Rekeningens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BSN", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BSN
		{
			get
			{
				return this._BSN;
			}
			set
			{
				if ((this._BSN != value))
				{
					this.OnBSNChanging(value);
					this.SendPropertyChanging();
					this._BSN = value;
					this.SendPropertyChanged("BSN");
					this.OnBSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voorletters", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Voorletters
		{
			get
			{
				return this._Voorletters;
			}
			set
			{
				if ((this._Voorletters != value))
				{
					this.OnVoorlettersChanging(value);
					this.SendPropertyChanging();
					this._Voorletters = value;
					this.SendPropertyChanged("Voorletters");
					this.OnVoorlettersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voornaam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Voornaam
		{
			get
			{
				return this._Voornaam;
			}
			set
			{
				if ((this._Voornaam != value))
				{
					this.OnVoornaamChanging(value);
					this.SendPropertyChanging();
					this._Voornaam = value;
					this.SendPropertyChanged("Voornaam");
					this.OnVoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Achternaam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Achternaam
		{
			get
			{
				return this._Achternaam;
			}
			set
			{
				if ((this._Achternaam != value))
				{
					this.OnAchternaamChanging(value);
					this.SendPropertyChanging();
					this._Achternaam = value;
					this.SendPropertyChanged("Achternaam");
					this.OnAchternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Woonplaats", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Woonplaats
		{
			get
			{
				return this._Woonplaats;
			}
			set
			{
				if ((this._Woonplaats != value))
				{
					this.OnWoonplaatsChanging(value);
					this.SendPropertyChanging();
					this._Woonplaats = value;
					this.SendPropertyChanged("Woonplaats");
					this.OnWoonplaatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefoonnummer", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Telefoonnummer
		{
			get
			{
				return this._Telefoonnummer;
			}
			set
			{
				if ((this._Telefoonnummer != value))
				{
					this.OnTelefoonnummerChanging(value);
					this.SendPropertyChanging();
					this._Telefoonnummer = value;
					this.SendPropertyChanged("Telefoonnummer");
					this.OnTelefoonnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klanten_Rekeningen", Storage="_Rekeningens", ThisKey="BSN", OtherKey="Rekeninghouder")]
		public EntitySet<Rekeningen> Rekeningens
		{
			get
			{
				return this._Rekeningens;
			}
			set
			{
				this._Rekeningens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rekeningens(Rekeningen entity)
		{
			this.SendPropertyChanging();
			entity.Klanten = this;
		}
		
		private void detach_Rekeningens(Rekeningen entity)
		{
			this.SendPropertyChanging();
			entity.Klanten = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rekeningen")]
	public partial class Rekeningen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IBAN;
		
		private string _Rekeninghouder;
		
		private double _Saldo;
		
		private string _Type;
		
		private System.DateTime _OpenDatum;
		
		private System.Nullable<System.DateTime> _SluitDatum;
		
		private EntityRef<Klanten> _Klanten;
		
		private EntityRef<Typen> _Typen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIBANChanging(string value);
    partial void OnIBANChanged();
    partial void OnRekeninghouderChanging(string value);
    partial void OnRekeninghouderChanged();
    partial void OnSaldoChanging(double value);
    partial void OnSaldoChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnOpenDatumChanging(System.DateTime value);
    partial void OnOpenDatumChanged();
    partial void OnSluitDatumChanging(System.Nullable<System.DateTime> value);
    partial void OnSluitDatumChanged();
    #endregion
		
		public Rekeningen()
		{
			this._Klanten = default(EntityRef<Klanten>);
			this._Typen = default(EntityRef<Typen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this.OnIBANChanging(value);
					this.SendPropertyChanging();
					this._IBAN = value;
					this.SendPropertyChanged("IBAN");
					this.OnIBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rekeninghouder", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string Rekeninghouder
		{
			get
			{
				return this._Rekeninghouder;
			}
			set
			{
				if ((this._Rekeninghouder != value))
				{
					if (this._Klanten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRekeninghouderChanging(value);
					this.SendPropertyChanging();
					this._Rekeninghouder = value;
					this.SendPropertyChanged("Rekeninghouder");
					this.OnRekeninghouderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Float NOT NULL")]
		public double Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this.OnSaldoChanging(value);
					this.SendPropertyChanging();
					this._Saldo = value;
					this.SendPropertyChanged("Saldo");
					this.OnSaldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					if (this._Typen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpenDatum", DbType="DateTime NOT NULL")]
		public System.DateTime OpenDatum
		{
			get
			{
				return this._OpenDatum;
			}
			set
			{
				if ((this._OpenDatum != value))
				{
					this.OnOpenDatumChanging(value);
					this.SendPropertyChanging();
					this._OpenDatum = value;
					this.SendPropertyChanged("OpenDatum");
					this.OnOpenDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SluitDatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> SluitDatum
		{
			get
			{
				return this._SluitDatum;
			}
			set
			{
				if ((this._SluitDatum != value))
				{
					this.OnSluitDatumChanging(value);
					this.SendPropertyChanging();
					this._SluitDatum = value;
					this.SendPropertyChanged("SluitDatum");
					this.OnSluitDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klanten_Rekeningen", Storage="_Klanten", ThisKey="Rekeninghouder", OtherKey="BSN", IsForeignKey=true)]
		public Klanten Klanten
		{
			get
			{
				return this._Klanten.Entity;
			}
			set
			{
				Klanten previousValue = this._Klanten.Entity;
				if (((previousValue != value) 
							|| (this._Klanten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klanten.Entity = null;
						previousValue.Rekeningens.Remove(this);
					}
					this._Klanten.Entity = value;
					if ((value != null))
					{
						value.Rekeningens.Add(this);
						this._Rekeninghouder = value.BSN;
					}
					else
					{
						this._Rekeninghouder = default(string);
					}
					this.SendPropertyChanged("Klanten");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Typen_Rekeningen", Storage="_Typen", ThisKey="Type", OtherKey="Naam", IsForeignKey=true)]
		public Typen Typen
		{
			get
			{
				return this._Typen.Entity;
			}
			set
			{
				Typen previousValue = this._Typen.Entity;
				if (((previousValue != value) 
							|| (this._Typen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Typen.Entity = null;
						previousValue.Rekeningens.Remove(this);
					}
					this._Typen.Entity = value;
					if ((value != null))
					{
						value.Rekeningens.Add(this);
						this._Type = value.Naam;
					}
					else
					{
						this._Type = default(string);
					}
					this.SendPropertyChanged("Typen");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
